game_name: "Clash of Piglin"
version: "1.0.0"

menu_buttons : ["Jouer", "Cr√©dits","Options", "Quitter"]
tile_size: 32


assets_path:
  logo: "assets/images/logo.png"
  background: "assets/images/background2.jpg"
  font: "assets/fonts/Minecraftia-Regular.ttf"

textures:
  lava: "assets/images/lava.png"
  netherrack : "assets/images/Netherrack.png"
  red_netherrack : "assets/images/Red_netherrack.png"
  blue_netherrack : "assets/images/Blue_netherrack.png"
  soulsand : "assets/images/Soulsand.png"

debug:
  give_gold:
    enabled: true
    amount: 300